test:
	python ne_tagger.py && python eval_ne_tagger.py ner_dev.key viterbi_prediction_file-rare

test-minimal:
	python ne_tagger.py -m && python eval_ne_tagger.py key-minimal viterbi_prediction_file-rare
